/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.kazurayam.gradle

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class DependencyInspectionPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("listJarsContainingClazz") {
            doLast {
                println("Hello from plugin 'com.kazurayam.gradle.DependencyInspectionPlugin'")
            }
        }
    }
}

/*
class ListJarsContainingClazzTask extends DefaultTask {
    @Input
    String dependencyName
    @Input
    String className
    @TaskAction
    void execute() {
        println "dependency: ${dependencyName}"
        println "class     : ${className}"
    }
}
 */